import { collection, getDocs } from "firebase/firestore";
import Head from "next/head";
import Header from "../components/Header";
import { mapPost } from "../components/mapPost";
import { NewsList } from "../components/NewsList";
import { db } from "../firebase";

export default function Home({ newsArticles }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Space+Mono:ital@1&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Header/>
      <NewsList newsArticles={newsArticles} />
    </div>
  );
}

// Code for fetching data from firestore using server-side rendering.
export async function getServerSideProps(context) {
  const ref = collection(db, "newsArticles");
  const docs = await getDocs(ref);
  const articles = [];
  docs.forEach((doc) => articles.push(mapPost(doc.data())));
  return {
    props: { newsArticles: articles },
  };
}
